Update psmisc from version 22.2 to 22.7
Version 22.2 is no longer available.

Also fix the psmisc compilation:
Avoid 'undefined reference to rpl_malloc' errors.