Minor update of gtkmm from 2.14.3 to 2.14.4
Fixes the following error when building (GCC 4.4.x):
recentinfo.cc:192: error: invalid conversion from 'gchar**' to 'const gchar**'